import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { getCatsData } from '../src/api/cats';
import 'bootstrap/dist/css/bootstrap.min.css';

import styles from '../styles/Home.module.css'
import { List } from '../src/components/list/list';
import { Spinner } from 'react-bootstrap';
import { useGetCats } from '../src/components/list/use-list';

export default function Home() {

  const { loading, data } = useGetCats();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main}`}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className='p-4 row d-flex align-item-center justify-content-between'>
          { loading && <Spinner animation="grow" variant="primary" />}
          { !loading && <List data={data} /> }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
